title: Vicente Herrera
description: > # this means to ignore newlines until "show_excerpts:"
  Documentation
  Page

theme: jekyll-theme-vicenteherrera

sass:
  style: compressed

plugins:
  - autoprefixer-rails
  - jekyll-seo-tag
  - jekyll-sitemap
